version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ai-quote-generator
    ports:
      - "8000:8000"
    environment:
      # Load from .env file
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - APP_NAME=${APP_NAME:-Swan}
      - APP_VERSION=${APP_VERSION:-1.0.0}
      - DEBUG=${DEBUG:-False}
      - HOST=${HOST:-0.0.0.0}
      - PORT=${PORT:-8000}
      - DEFAULT_MODEL=${DEFAULT_MODEL:-gemini-1.5-flash}
      - MAX_TOKENS=${MAX_TOKENS:-530}
      - TEMPERATURE=${TEMPERATURE:-0.7}
    env_file:
      - .env
    volumes:
      # Mount code for development (comment out for production)
      - .:/app
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8000/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - ai-quote-network

networks:
  ai-quote-network:
    driver: bridge
